Update playa

diff --git a/playa b/playa
--- a/playa
+++ b/playa
@@ -83,15 +83,17 @@ case "$1" in
 		done < <(find "$f/" \( "${find_args[@]}" \) -print0)
 																 
 		for index in "${!playlist[@]}" ; do
-			# we better implement || break to interrupt the loop on CTRL+C
+			# we better implement || break to be able to interrupt the loop on CTRL+C if STDIN fails
 			# It's because of ffplay, it has set a signal handler for SIGINT, and fails to reset it
 			# @TODO: testing a better solution with trap 'trap - SIGINT; kill -INT "$$"' INT or
 			# trap 'trap - INT; kill -INT "$$"' INT ... or use key bindings (?) 
 			# http://stackoverflow.com/questions/4200800/in-bash-how-do-i-bind-a-function-key-to-a-command
-			if hash ffmpeg 2>/dev/null ; then
+			if hash mplayer 2>/dev/null ; then
+				mplayer -ao "${playlist[index]}" || break
+			elif hash ffmpeg 2>/dev/null ; then
 				ffplay -nodisp -hide_banner -autoexit "${playlist[index]}" || break
-			elif hash aplay 2>/dev/null ; then
-				aplay "${playlist[index]}" || break
+			elif hash sox 2>/dev/null ; then
+				play "${playlist[index]}" || break
 			else
 				ErrMissingDep
 				exit 1
